config/routes.rb
Rails.application.routes.draw do
  get 'users/login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get  "pages/about_us"
  get "pages/test"
  root "pages#test"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def test
    end
    def about_us
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecondApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="assets/css/main.css"/><noscript>
    <link rel="stylesheet" href="assets/css/noscript.css"></noscript>
  </head>

  <body>

        <nav id="nav">
          <ul>
            <li><%= link_to "Home", pages_test_path %></li>
            <li>
              <%= link_to "Dropdown", pages_test_path %>
              <ul>
                <li><a href="#">Lorem ipsum dolor</a></li>
                <li><a href="#">Magna phasellus</a></li>
                <li><a href="#">Etiam dolore nisl</a></li>
                <li>
                  <a href="#">And a submenu &hellip;</a>
                  <ul>
                    <li><a href="#">Lorem ipsum dolor</a></li>
                    <li><a href="#">Phasellus consequat</a></li>
                    <li><a href="#">Magna phasellus</a></li>
                    <li><a href="#">Etiam dolore nisl</a></li>
                  </ul>
                </li>
                <li><a href="#">Veroeros feugiat</a></li>
              </ul>
            </li>
            <li><%= link_to 'Left Sidebar', users_login_path %></li>
            <li><a href="right-sidebar.html">Right Sidebar</a></li>
            <li><a href="no-sidebar.html">No Sidebar</a></li>
          </ul>
        </nav>
      </div>
        <hr>
        <br>
    <%= yield %>
      <div id="footer">
              <div class="copyright">
                <ul class="menu">
                  <li>&copy; Untitled. All rights reserved.</li>
                  <li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/test.html.erb
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque illo, velit quisquam autem ipsam fugit. Et, accusantium at. Deleniti molestias repellendus perferendis aperiam, illo atque nisi facere. Exercitationem, voluptate aliquid. Neque nihil laborum, at quaerat deleniti consequatur deserunt distinctio consequuntur veniam ipsa nulla illo accusantium totam rem ratione omnis amet nostrum voluptates quibusdam dignissimos voluptatem ea. Quo alias veniam ipsum. Voluptatibus doloribus, atque suscipit cum quo asperiores provident ea assumenda nobis quae inventore at eaque, ex, impedit consequatur a! Ullam officiis ipsam recusandae obcaecati libero nisi id consectetur eum neque!</p>



<%= image_tag 'helios.jpg', :class => "imagen" %>

app/views/users/login.html.erb
<h1>Login</h1>